version: '3.8'

services:
  postgres:
    container_name: db_autoserviceST2
    image: library/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoservice_st2
    restart: unless-stopped

#  app:
#    build:
#      context: .
#      dockerfile: docker/services/app/Dockerfile
#    container_name: app_langtrain
#    environment:
#      - PORT=8080
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/langtrain
#      - SPRING_DATASOURSE_USERNAME=postgres
#      - SPRING_DATASOURSE_PASSWORD=postgres
#      - SPRING_DATASOURSE_HIKARI_SCHEMA=langtrain
##      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
##      - SPRING_FLYWAY_ENABLED=true
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#    links:
#       - postgres
